/** @type {import('tailwindcss').Config} */
import forms from '@tailwindcss/forms'
import containerQueries from '@tailwindcss/container-queries'

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    borderRadius: {
      none: '0px',
      sm: '0px',
      DEFAULT: '0px',
      md: '0px',
      lg: '0px',
      xl: '0px',
      '2xl': '0px',
      '3xl': '0px',
      full: '9999px',
    },
    extend: {
      colors: {
        'on-tertiary': '#003257',
        'surface-bright': '#393939',
        'surface-dim': '#131313',
        tertiary: '#9ccaff',
        'surface-container': '#201f1f',
        'surface-container-highest': '#353534',
        'on-primary-container': '#572000',
        'on-primary-fixed-variant': '#7a3000',
        'outline-variant': '#5a4136',
        'primary-container': '#ff6b00',
        'on-tertiary-container': '#003357',
        'on-tertiary-fixed': '#001d35',
        'inverse-primary': '#a04100',
        error: '#ffb4ab',
        'surface-tint': '#ffb693',
        surface: '#131313',
        'on-primary-fixed': '#351000',
        background: '#131313',
        'on-error-container': '#ffdad6',
        'on-surface': '#e5e2e1',
        secondary: '#bdf4ff',
        'on-secondary': '#00363d',
        'on-tertiary-fixed-variant': '#00497b',
        'secondary-fixed': '#9cf0ff',
        'secondary-fixed-dim': '#00daf3',
        'surface-container-lowest': '#0e0e0e',
        outline: '#a98a7d',
        'surface-container-low': '#1c1b1b',
        'on-secondary-fixed': '#001f24',
        'inverse-on-surface': '#313030',
        'tertiary-container': '#059eff',
        'tertiary-fixed': '#d0e4ff',
        'on-surface-variant': '#e2bfb0',
        'on-secondary-fixed-variant': '#004f58',
        'surface-container-high': '#2a2a2a',
        'on-secondary-container': '#00616d',
        'on-primary': '#561f00',
        'on-background': '#e5e2e1',
        'error-container': '#93000a',
        'secondary-container': '#00e3fd',
        'surface-variant': '#353534',
        primary: '#ffb693',
        'inverse-surface': '#e5e2e1',
        'primary-fixed-dim': '#ffb693',
        'tertiary-fixed-dim': '#9ccaff',
        'on-error': '#690005',
        'primary-fixed': '#ffdbcc',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'ui-sans-serif', 'system-ui'],
        body: ['Inter', 'ui-sans-serif', 'system-ui'],
        label: ['Inter', 'ui-sans-serif', 'system-ui'],
        sans: ['Inter', 'ui-sans-serif', 'system-ui'],
      },
    },
  },
  plugins: [forms, containerQueries],
}

